/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables;


import com.grb.indonesia.entity.Keys;
import com.grb.indonesia.entity.Pinpoint;
import com.grb.indonesia.entity.tables.records.AlarmHistoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmHistory extends TableImpl<AlarmHistoryRecord> {

    private static final long serialVersionUID = -1076061480;

    /**
     * The reference instance of <code>pinpoint.alarm_history</code>
     */
    public static final AlarmHistory ALARM_HISTORY = new AlarmHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlarmHistoryRecord> getRecordType() {
        return AlarmHistoryRecord.class;
    }

    /**
     * The column <code>pinpoint.alarm_history.history_id</code>.
     */
    public final TableField<AlarmHistoryRecord, UInteger> HISTORY_ID = createField("history_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_history.application_id</code>.
     */
    public final TableField<AlarmHistoryRecord, String> APPLICATION_ID = createField("application_id", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_history.checker_name</code>.
     */
    public final TableField<AlarmHistoryRecord, String> CHECKER_NAME = createField("checker_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_history.detected</code>.
     */
    public final TableField<AlarmHistoryRecord, String> DETECTED = createField("detected", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

    /**
     * The column <code>pinpoint.alarm_history.sequence_count</code>.
     */
    public final TableField<AlarmHistoryRecord, Integer> SEQUENCE_COUNT = createField("sequence_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>pinpoint.alarm_history.timing_count</code>.
     */
    public final TableField<AlarmHistoryRecord, Integer> TIMING_COUNT = createField("timing_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>pinpoint.alarm_history</code> table reference
     */
    public AlarmHistory() {
        this("alarm_history", null);
    }

    /**
     * Create an aliased <code>pinpoint.alarm_history</code> table reference
     */
    public AlarmHistory(String alias) {
        this(alias, ALARM_HISTORY);
    }

    private AlarmHistory(String alias, Table<AlarmHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlarmHistory(String alias, Table<AlarmHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AlarmHistoryRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ALARM_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlarmHistoryRecord> getPrimaryKey() {
        return Keys.KEY_ALARM_HISTORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlarmHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<AlarmHistoryRecord>>asList(Keys.KEY_ALARM_HISTORY_PRIMARY, Keys.KEY_ALARM_HISTORY_APPLICATION_ID_CHECKER_NAME_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistory as(String alias) {
        return new AlarmHistory(alias, this);
    }

    /**
     * Rename this table
     */
    public AlarmHistory rename(String name) {
        return new AlarmHistory(name, null);
    }
}
