/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables;


import com.grb.indonesia.entity.Keys;
import com.grb.indonesia.entity.Pinpoint;
import com.grb.indonesia.entity.tables.records.BatchJobSeqRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobSeq extends TableImpl<BatchJobSeqRecord> {

    private static final long serialVersionUID = 1734453947;

    /**
     * The reference instance of <code>pinpoint.BATCH_JOB_SEQ</code>
     */
    public static final BatchJobSeq BATCH_JOB_SEQ = new BatchJobSeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchJobSeqRecord> getRecordType() {
        return BatchJobSeqRecord.class;
    }

    /**
     * The column <code>pinpoint.BATCH_JOB_SEQ.ID</code>.
     */
    public final TableField<BatchJobSeqRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pinpoint.BATCH_JOB_SEQ.UNIQUE_KEY</code>.
     */
    public final TableField<BatchJobSeqRecord, String> UNIQUE_KEY = createField("UNIQUE_KEY", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

    /**
     * Create a <code>pinpoint.BATCH_JOB_SEQ</code> table reference
     */
    public BatchJobSeq() {
        this("BATCH_JOB_SEQ", null);
    }

    /**
     * Create an aliased <code>pinpoint.BATCH_JOB_SEQ</code> table reference
     */
    public BatchJobSeq(String alias) {
        this(alias, BATCH_JOB_SEQ);
    }

    private BatchJobSeq(String alias, Table<BatchJobSeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchJobSeq(String alias, Table<BatchJobSeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BatchJobSeqRecord>> getKeys() {
        return Arrays.<UniqueKey<BatchJobSeqRecord>>asList(Keys.KEY_BATCH_JOB_SEQ_UNIQUE_KEY_UN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobSeq as(String alias) {
        return new BatchJobSeq(alias, this);
    }

    /**
     * Rename this table
     */
    public BatchJobSeq rename(String name) {
        return new BatchJobSeq(name, null);
    }
}
