/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables;


import com.grb.indonesia.entity.Keys;
import com.grb.indonesia.entity.Pinpoint;
import com.grb.indonesia.entity.tables.records.BatchJobInstanceRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobInstance extends TableImpl<BatchJobInstanceRecord> {

    private static final long serialVersionUID = 1329874420;

    /**
     * The reference instance of <code>pinpoint.BATCH_JOB_INSTANCE</code>
     */
    public static final BatchJobInstance BATCH_JOB_INSTANCE = new BatchJobInstance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchJobInstanceRecord> getRecordType() {
        return BatchJobInstanceRecord.class;
    }

    /**
     * The column <code>pinpoint.BATCH_JOB_INSTANCE.JOB_INSTANCE_ID</code>.
     */
    public final TableField<BatchJobInstanceRecord, Long> JOB_INSTANCE_ID = createField("JOB_INSTANCE_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pinpoint.BATCH_JOB_INSTANCE.VERSION</code>.
     */
    public final TableField<BatchJobInstanceRecord, Long> VERSION = createField("VERSION", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pinpoint.BATCH_JOB_INSTANCE.JOB_NAME</code>.
     */
    public final TableField<BatchJobInstanceRecord, String> JOB_NAME = createField("JOB_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>pinpoint.BATCH_JOB_INSTANCE.JOB_KEY</code>.
     */
    public final TableField<BatchJobInstanceRecord, String> JOB_KEY = createField("JOB_KEY", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * Create a <code>pinpoint.BATCH_JOB_INSTANCE</code> table reference
     */
    public BatchJobInstance() {
        this("BATCH_JOB_INSTANCE", null);
    }

    /**
     * Create an aliased <code>pinpoint.BATCH_JOB_INSTANCE</code> table reference
     */
    public BatchJobInstance(String alias) {
        this(alias, BATCH_JOB_INSTANCE);
    }

    private BatchJobInstance(String alias, Table<BatchJobInstanceRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchJobInstance(String alias, Table<BatchJobInstanceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BatchJobInstanceRecord> getPrimaryKey() {
        return Keys.KEY_BATCH_JOB_INSTANCE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BatchJobInstanceRecord>> getKeys() {
        return Arrays.<UniqueKey<BatchJobInstanceRecord>>asList(Keys.KEY_BATCH_JOB_INSTANCE_PRIMARY, Keys.KEY_BATCH_JOB_INSTANCE_JOB_INST_UN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobInstance as(String alias) {
        return new BatchJobInstance(alias, this);
    }

    /**
     * Rename this table
     */
    public BatchJobInstance rename(String name) {
        return new BatchJobInstance(name, null);
    }
}
