/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables;


import com.grb.indonesia.entity.Keys;
import com.grb.indonesia.entity.Pinpoint;
import com.grb.indonesia.entity.tables.records.PuserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Puser extends TableImpl<PuserRecord> {

    private static final long serialVersionUID = 1018902831;

    /**
     * The reference instance of <code>pinpoint.puser</code>
     */
    public static final Puser PUSER = new Puser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PuserRecord> getRecordType() {
        return PuserRecord.class;
    }

    /**
     * The column <code>pinpoint.puser.number</code>.
     */
    public final TableField<PuserRecord, UInteger> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>pinpoint.puser.user_id</code>.
     */
    public final TableField<PuserRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>pinpoint.puser.name</code>.
     */
    public final TableField<PuserRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

    /**
     * The column <code>pinpoint.puser.department</code>.
     */
    public final TableField<PuserRecord, String> DEPARTMENT = createField("department", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

    /**
     * The column <code>pinpoint.puser.phonenumber</code>.
     */
    public final TableField<PuserRecord, String> PHONENUMBER = createField("phonenumber", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>pinpoint.puser.email</code>.
     */
    public final TableField<PuserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>pinpoint.puser</code> table reference
     */
    public Puser() {
        this("puser", null);
    }

    /**
     * Create an aliased <code>pinpoint.puser</code> table reference
     */
    public Puser(String alias) {
        this(alias, PUSER);
    }

    private Puser(String alias, Table<PuserRecord> aliased) {
        this(alias, aliased, null);
    }

    private Puser(String alias, Table<PuserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PuserRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PuserRecord> getPrimaryKey() {
        return Keys.KEY_PUSER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PuserRecord>> getKeys() {
        return Arrays.<UniqueKey<PuserRecord>>asList(Keys.KEY_PUSER_PRIMARY, Keys.KEY_PUSER_USER_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Puser as(String alias) {
        return new Puser(alias, this);
    }

    /**
     * Rename this table
     */
    public Puser rename(String name) {
        return new Puser(name, null);
    }
}
