/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq;


import com.grb.indonesia.jooq.data.jooq.tables.AlarmHistory;
import com.grb.indonesia.jooq.data.jooq.tables.AlarmRule;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecution;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionContext;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionParams;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionSeq;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobInstance;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobSeq;
import com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecution;
import com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecutionContext;
import com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecutionSeq;
import com.grb.indonesia.jooq.data.jooq.tables.Puser;
import com.grb.indonesia.jooq.data.jooq.tables.UserGroup;
import com.grb.indonesia.jooq.data.jooq.tables.UserGroupMember;
import com.grb.indonesia.jooq.data.jooq.tables.records.AlarmHistoryRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.AlarmRuleRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchJobExecutionContextRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchJobExecutionParamsRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchJobExecutionRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchJobExecutionSeqRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchJobInstanceRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchJobSeqRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchStepExecutionContextRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchStepExecutionRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchStepExecutionSeqRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.PuserRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.UserGroupMemberRecord;
import com.grb.indonesia.jooq.data.jooq.tables.records.UserGroupRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships between tables of the <code>pinpoint</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AlarmHistoryRecord, UInteger> IDENTITY_ALARM_HISTORY = Identities0.IDENTITY_ALARM_HISTORY;
    public static final Identity<AlarmRuleRecord, UInteger> IDENTITY_ALARM_RULE = Identities0.IDENTITY_ALARM_RULE;
    public static final Identity<PuserRecord, UInteger> IDENTITY_PUSER = Identities0.IDENTITY_PUSER;
    public static final Identity<UserGroupRecord, UInteger> IDENTITY_USER_GROUP = Identities0.IDENTITY_USER_GROUP;
    public static final Identity<UserGroupMemberRecord, UInteger> IDENTITY_USER_GROUP_MEMBER = Identities0.IDENTITY_USER_GROUP_MEMBER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AlarmHistoryRecord> KEY_ALARM_HISTORY_PRIMARY = UniqueKeys0.KEY_ALARM_HISTORY_PRIMARY;
    public static final UniqueKey<AlarmHistoryRecord> KEY_ALARM_HISTORY_APPLICATION_ID_CHECKER_NAME_IDX = UniqueKeys0.KEY_ALARM_HISTORY_APPLICATION_ID_CHECKER_NAME_IDX;
    public static final UniqueKey<AlarmRuleRecord> KEY_ALARM_RULE_PRIMARY = UniqueKeys0.KEY_ALARM_RULE_PRIMARY;
    public static final UniqueKey<AlarmRuleRecord> KEY_ALARM_RULE_APPLICATION_ID_CHECKER_NAME_USER_GROUP_ID_IDX = UniqueKeys0.KEY_ALARM_RULE_APPLICATION_ID_CHECKER_NAME_USER_GROUP_ID_IDX;
    public static final UniqueKey<BatchJobExecutionRecord> KEY_BATCH_JOB_EXECUTION_PRIMARY = UniqueKeys0.KEY_BATCH_JOB_EXECUTION_PRIMARY;
    public static final UniqueKey<BatchJobExecutionContextRecord> KEY_BATCH_JOB_EXECUTION_CONTEXT_PRIMARY = UniqueKeys0.KEY_BATCH_JOB_EXECUTION_CONTEXT_PRIMARY;
    public static final UniqueKey<BatchJobExecutionSeqRecord> KEY_BATCH_JOB_EXECUTION_SEQ_UNIQUE_KEY_UN = UniqueKeys0.KEY_BATCH_JOB_EXECUTION_SEQ_UNIQUE_KEY_UN;
    public static final UniqueKey<BatchJobInstanceRecord> KEY_BATCH_JOB_INSTANCE_PRIMARY = UniqueKeys0.KEY_BATCH_JOB_INSTANCE_PRIMARY;
    public static final UniqueKey<BatchJobInstanceRecord> KEY_BATCH_JOB_INSTANCE_JOB_INST_UN = UniqueKeys0.KEY_BATCH_JOB_INSTANCE_JOB_INST_UN;
    public static final UniqueKey<BatchJobSeqRecord> KEY_BATCH_JOB_SEQ_UNIQUE_KEY_UN = UniqueKeys0.KEY_BATCH_JOB_SEQ_UNIQUE_KEY_UN;
    public static final UniqueKey<BatchStepExecutionRecord> KEY_BATCH_STEP_EXECUTION_PRIMARY = UniqueKeys0.KEY_BATCH_STEP_EXECUTION_PRIMARY;
    public static final UniqueKey<BatchStepExecutionContextRecord> KEY_BATCH_STEP_EXECUTION_CONTEXT_PRIMARY = UniqueKeys0.KEY_BATCH_STEP_EXECUTION_CONTEXT_PRIMARY;
    public static final UniqueKey<BatchStepExecutionSeqRecord> KEY_BATCH_STEP_EXECUTION_SEQ_UNIQUE_KEY_UN = UniqueKeys0.KEY_BATCH_STEP_EXECUTION_SEQ_UNIQUE_KEY_UN;
    public static final UniqueKey<PuserRecord> KEY_PUSER_PRIMARY = UniqueKeys0.KEY_PUSER_PRIMARY;
    public static final UniqueKey<PuserRecord> KEY_PUSER_USER_ID_IDX = UniqueKeys0.KEY_PUSER_USER_ID_IDX;
    public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_PRIMARY = UniqueKeys0.KEY_USER_GROUP_PRIMARY;
    public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_ID_IDX = UniqueKeys0.KEY_USER_GROUP_ID_IDX;
    public static final UniqueKey<UserGroupMemberRecord> KEY_USER_GROUP_MEMBER_PRIMARY = UniqueKeys0.KEY_USER_GROUP_MEMBER_PRIMARY;
    public static final UniqueKey<UserGroupMemberRecord> KEY_USER_GROUP_MEMBER_USER_GROUP_ID_MEMBER_ID_IDX = UniqueKeys0.KEY_USER_GROUP_MEMBER_USER_GROUP_ID_MEMBER_ID_IDX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BatchJobExecutionRecord, BatchJobInstanceRecord> JOB_INST_EXEC_FK = ForeignKeys0.JOB_INST_EXEC_FK;
    public static final ForeignKey<BatchJobExecutionContextRecord, BatchJobExecutionRecord> JOB_EXEC_CTX_FK = ForeignKeys0.JOB_EXEC_CTX_FK;
    public static final ForeignKey<BatchJobExecutionParamsRecord, BatchJobExecutionRecord> JOB_EXEC_PARAMS_FK = ForeignKeys0.JOB_EXEC_PARAMS_FK;
    public static final ForeignKey<BatchStepExecutionRecord, BatchJobExecutionRecord> JOB_EXEC_STEP_FK = ForeignKeys0.JOB_EXEC_STEP_FK;
    public static final ForeignKey<BatchStepExecutionContextRecord, BatchStepExecutionRecord> STEP_EXEC_CTX_FK = ForeignKeys0.STEP_EXEC_CTX_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AlarmHistoryRecord, UInteger> IDENTITY_ALARM_HISTORY = createIdentity(AlarmHistory.ALARM_HISTORY, AlarmHistory.ALARM_HISTORY.HISTORY_ID);
        public static Identity<AlarmRuleRecord, UInteger> IDENTITY_ALARM_RULE = createIdentity(AlarmRule.ALARM_RULE, AlarmRule.ALARM_RULE.RULE_ID);
        public static Identity<PuserRecord, UInteger> IDENTITY_PUSER = createIdentity(Puser.PUSER, Puser.PUSER.NUMBER);
        public static Identity<UserGroupRecord, UInteger> IDENTITY_USER_GROUP = createIdentity(UserGroup.USER_GROUP, UserGroup.USER_GROUP.NUMBER);
        public static Identity<UserGroupMemberRecord, UInteger> IDENTITY_USER_GROUP_MEMBER = createIdentity(UserGroupMember.USER_GROUP_MEMBER, UserGroupMember.USER_GROUP_MEMBER.NUMBER);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AlarmHistoryRecord> KEY_ALARM_HISTORY_PRIMARY = createUniqueKey(AlarmHistory.ALARM_HISTORY, "KEY_alarm_history_PRIMARY", AlarmHistory.ALARM_HISTORY.HISTORY_ID);
        public static final UniqueKey<AlarmHistoryRecord> KEY_ALARM_HISTORY_APPLICATION_ID_CHECKER_NAME_IDX = createUniqueKey(AlarmHistory.ALARM_HISTORY, "KEY_alarm_history_application_id_checker_name_idx", AlarmHistory.ALARM_HISTORY.APPLICATION_ID, AlarmHistory.ALARM_HISTORY.CHECKER_NAME);
        public static final UniqueKey<AlarmRuleRecord> KEY_ALARM_RULE_PRIMARY = createUniqueKey(AlarmRule.ALARM_RULE, "KEY_alarm_rule_PRIMARY", AlarmRule.ALARM_RULE.RULE_ID);
        public static final UniqueKey<AlarmRuleRecord> KEY_ALARM_RULE_APPLICATION_ID_CHECKER_NAME_USER_GROUP_ID_IDX = createUniqueKey(AlarmRule.ALARM_RULE, "KEY_alarm_rule_application_id_checker_name_user_group_id_idx", AlarmRule.ALARM_RULE.APPLICATION_ID, AlarmRule.ALARM_RULE.USER_GROUP_ID, AlarmRule.ALARM_RULE.CHECKER_NAME);
        public static final UniqueKey<BatchJobExecutionRecord> KEY_BATCH_JOB_EXECUTION_PRIMARY = createUniqueKey(BatchJobExecution.BATCH_JOB_EXECUTION, "KEY_BATCH_JOB_EXECUTION_PRIMARY", BatchJobExecution.BATCH_JOB_EXECUTION.JOB_EXECUTION_ID);
        public static final UniqueKey<BatchJobExecutionContextRecord> KEY_BATCH_JOB_EXECUTION_CONTEXT_PRIMARY = createUniqueKey(BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT, "KEY_BATCH_JOB_EXECUTION_CONTEXT_PRIMARY", BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID);
        public static final UniqueKey<BatchJobExecutionSeqRecord> KEY_BATCH_JOB_EXECUTION_SEQ_UNIQUE_KEY_UN = createUniqueKey(BatchJobExecutionSeq.BATCH_JOB_EXECUTION_SEQ, "KEY_BATCH_JOB_EXECUTION_SEQ_UNIQUE_KEY_UN", BatchJobExecutionSeq.BATCH_JOB_EXECUTION_SEQ.UNIQUE_KEY);
        public static final UniqueKey<BatchJobInstanceRecord> KEY_BATCH_JOB_INSTANCE_PRIMARY = createUniqueKey(BatchJobInstance.BATCH_JOB_INSTANCE, "KEY_BATCH_JOB_INSTANCE_PRIMARY", BatchJobInstance.BATCH_JOB_INSTANCE.JOB_INSTANCE_ID);
        public static final UniqueKey<BatchJobInstanceRecord> KEY_BATCH_JOB_INSTANCE_JOB_INST_UN = createUniqueKey(BatchJobInstance.BATCH_JOB_INSTANCE, "KEY_BATCH_JOB_INSTANCE_JOB_INST_UN", BatchJobInstance.BATCH_JOB_INSTANCE.JOB_NAME, BatchJobInstance.BATCH_JOB_INSTANCE.JOB_KEY);
        public static final UniqueKey<BatchJobSeqRecord> KEY_BATCH_JOB_SEQ_UNIQUE_KEY_UN = createUniqueKey(BatchJobSeq.BATCH_JOB_SEQ, "KEY_BATCH_JOB_SEQ_UNIQUE_KEY_UN", BatchJobSeq.BATCH_JOB_SEQ.UNIQUE_KEY);
        public static final UniqueKey<BatchStepExecutionRecord> KEY_BATCH_STEP_EXECUTION_PRIMARY = createUniqueKey(BatchStepExecution.BATCH_STEP_EXECUTION, "KEY_BATCH_STEP_EXECUTION_PRIMARY", BatchStepExecution.BATCH_STEP_EXECUTION.STEP_EXECUTION_ID);
        public static final UniqueKey<BatchStepExecutionContextRecord> KEY_BATCH_STEP_EXECUTION_CONTEXT_PRIMARY = createUniqueKey(BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT, "KEY_BATCH_STEP_EXECUTION_CONTEXT_PRIMARY", BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID);
        public static final UniqueKey<BatchStepExecutionSeqRecord> KEY_BATCH_STEP_EXECUTION_SEQ_UNIQUE_KEY_UN = createUniqueKey(BatchStepExecutionSeq.BATCH_STEP_EXECUTION_SEQ, "KEY_BATCH_STEP_EXECUTION_SEQ_UNIQUE_KEY_UN", BatchStepExecutionSeq.BATCH_STEP_EXECUTION_SEQ.UNIQUE_KEY);
        public static final UniqueKey<PuserRecord> KEY_PUSER_PRIMARY = createUniqueKey(Puser.PUSER, "KEY_puser_PRIMARY", Puser.PUSER.NUMBER);
        public static final UniqueKey<PuserRecord> KEY_PUSER_USER_ID_IDX = createUniqueKey(Puser.PUSER, "KEY_puser_user_id_idx", Puser.PUSER.USER_ID);
        public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_PRIMARY = createUniqueKey(UserGroup.USER_GROUP, "KEY_user_group_PRIMARY", UserGroup.USER_GROUP.NUMBER);
        public static final UniqueKey<UserGroupRecord> KEY_USER_GROUP_ID_IDX = createUniqueKey(UserGroup.USER_GROUP, "KEY_user_group_id_idx", UserGroup.USER_GROUP.ID);
        public static final UniqueKey<UserGroupMemberRecord> KEY_USER_GROUP_MEMBER_PRIMARY = createUniqueKey(UserGroupMember.USER_GROUP_MEMBER, "KEY_user_group_member_PRIMARY", UserGroupMember.USER_GROUP_MEMBER.NUMBER);
        public static final UniqueKey<UserGroupMemberRecord> KEY_USER_GROUP_MEMBER_USER_GROUP_ID_MEMBER_ID_IDX = createUniqueKey(UserGroupMember.USER_GROUP_MEMBER, "KEY_user_group_member_user_group_id_member_id_idx", UserGroupMember.USER_GROUP_MEMBER.USER_GROUP_ID, UserGroupMember.USER_GROUP_MEMBER.MEMBER_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<BatchJobExecutionRecord, BatchJobInstanceRecord> JOB_INST_EXEC_FK = createForeignKey(com.grb.indonesia.jooq.data.jooq.Keys.KEY_BATCH_JOB_INSTANCE_PRIMARY, BatchJobExecution.BATCH_JOB_EXECUTION, "JOB_INST_EXEC_FK", BatchJobExecution.BATCH_JOB_EXECUTION.JOB_INSTANCE_ID);
        public static final ForeignKey<BatchJobExecutionContextRecord, BatchJobExecutionRecord> JOB_EXEC_CTX_FK = createForeignKey(com.grb.indonesia.jooq.data.jooq.Keys.KEY_BATCH_JOB_EXECUTION_PRIMARY, BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT, "JOB_EXEC_CTX_FK", BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID);
        public static final ForeignKey<BatchJobExecutionParamsRecord, BatchJobExecutionRecord> JOB_EXEC_PARAMS_FK = createForeignKey(com.grb.indonesia.jooq.data.jooq.Keys.KEY_BATCH_JOB_EXECUTION_PRIMARY, BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS, "JOB_EXEC_PARAMS_FK", BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID);
        public static final ForeignKey<BatchStepExecutionRecord, BatchJobExecutionRecord> JOB_EXEC_STEP_FK = createForeignKey(com.grb.indonesia.jooq.data.jooq.Keys.KEY_BATCH_JOB_EXECUTION_PRIMARY, BatchStepExecution.BATCH_STEP_EXECUTION, "JOB_EXEC_STEP_FK", BatchStepExecution.BATCH_STEP_EXECUTION.JOB_EXECUTION_ID);
        public static final ForeignKey<BatchStepExecutionContextRecord, BatchStepExecutionRecord> STEP_EXEC_CTX_FK = createForeignKey(com.grb.indonesia.jooq.data.jooq.Keys.KEY_BATCH_STEP_EXECUTION_PRIMARY, BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT, "STEP_EXEC_CTX_FK", BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID);
    }
}
