/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq;


import com.grb.indonesia.jooq.data.jooq.tables.AlarmHistory;
import com.grb.indonesia.jooq.data.jooq.tables.AlarmRule;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecution;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionContext;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionParams;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionSeq;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobInstance;
import com.grb.indonesia.jooq.data.jooq.tables.BatchJobSeq;
import com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecution;
import com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecutionContext;
import com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecutionSeq;
import com.grb.indonesia.jooq.data.jooq.tables.Puser;
import com.grb.indonesia.jooq.data.jooq.tables.TestDate;
import com.grb.indonesia.jooq.data.jooq.tables.UserGroup;
import com.grb.indonesia.jooq.data.jooq.tables.UserGroupMember;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in pinpoint
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pinpoint.alarm_history</code>.
     */
    public static final AlarmHistory ALARM_HISTORY = com.grb.indonesia.jooq.data.jooq.tables.AlarmHistory.ALARM_HISTORY;

    /**
     * The table <code>pinpoint.alarm_rule</code>.
     */
    public static final AlarmRule ALARM_RULE = com.grb.indonesia.jooq.data.jooq.tables.AlarmRule.ALARM_RULE;

    /**
     * The table <code>pinpoint.BATCH_JOB_EXECUTION</code>.
     */
    public static final BatchJobExecution BATCH_JOB_EXECUTION = com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecution.BATCH_JOB_EXECUTION;

    /**
     * The table <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT</code>.
     */
    public static final BatchJobExecutionContext BATCH_JOB_EXECUTION_CONTEXT = com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT;

    /**
     * The table <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS</code>.
     */
    public static final BatchJobExecutionParams BATCH_JOB_EXECUTION_PARAMS = com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS;

    /**
     * The table <code>pinpoint.BATCH_JOB_EXECUTION_SEQ</code>.
     */
    public static final BatchJobExecutionSeq BATCH_JOB_EXECUTION_SEQ = com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionSeq.BATCH_JOB_EXECUTION_SEQ;

    /**
     * The table <code>pinpoint.BATCH_JOB_INSTANCE</code>.
     */
    public static final BatchJobInstance BATCH_JOB_INSTANCE = com.grb.indonesia.jooq.data.jooq.tables.BatchJobInstance.BATCH_JOB_INSTANCE;

    /**
     * The table <code>pinpoint.BATCH_JOB_SEQ</code>.
     */
    public static final BatchJobSeq BATCH_JOB_SEQ = com.grb.indonesia.jooq.data.jooq.tables.BatchJobSeq.BATCH_JOB_SEQ;

    /**
     * The table <code>pinpoint.BATCH_STEP_EXECUTION</code>.
     */
    public static final BatchStepExecution BATCH_STEP_EXECUTION = com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecution.BATCH_STEP_EXECUTION;

    /**
     * The table <code>pinpoint.BATCH_STEP_EXECUTION_CONTEXT</code>.
     */
    public static final BatchStepExecutionContext BATCH_STEP_EXECUTION_CONTEXT = com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT;

    /**
     * The table <code>pinpoint.BATCH_STEP_EXECUTION_SEQ</code>.
     */
    public static final BatchStepExecutionSeq BATCH_STEP_EXECUTION_SEQ = com.grb.indonesia.jooq.data.jooq.tables.BatchStepExecutionSeq.BATCH_STEP_EXECUTION_SEQ;

    /**
     * The table <code>pinpoint.puser</code>.
     */
    public static final Puser PUSER = com.grb.indonesia.jooq.data.jooq.tables.Puser.PUSER;

    /**
     * The table <code>pinpoint.test_date</code>.
     */
    public static final TestDate TEST_DATE = com.grb.indonesia.jooq.data.jooq.tables.TestDate.TEST_DATE;

    /**
     * The table <code>pinpoint.user_group</code>.
     */
    public static final UserGroup USER_GROUP = com.grb.indonesia.jooq.data.jooq.tables.UserGroup.USER_GROUP;

    /**
     * The table <code>pinpoint.user_group_member</code>.
     */
    public static final UserGroupMember USER_GROUP_MEMBER = com.grb.indonesia.jooq.data.jooq.tables.UserGroupMember.USER_GROUP_MEMBER;
}
