/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq.tables;


import com.grb.indonesia.jooq.data.jooq.Keys;
import com.grb.indonesia.jooq.data.jooq.Pinpoint;
import com.grb.indonesia.jooq.data.jooq.tables.records.AlarmRuleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmRule extends TableImpl<AlarmRuleRecord> {

    private static final long serialVersionUID = -1108148798;

    /**
     * The reference instance of <code>pinpoint.alarm_rule</code>
     */
    public static final AlarmRule ALARM_RULE = new AlarmRule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlarmRuleRecord> getRecordType() {
        return AlarmRuleRecord.class;
    }

    /**
     * The column <code>pinpoint.alarm_rule.rule_id</code>.
     */
    public final TableField<AlarmRuleRecord, UInteger> RULE_ID = createField("rule_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_rule.application_id</code>.
     */
    public final TableField<AlarmRuleRecord, String> APPLICATION_ID = createField("application_id", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_rule.service_type</code>.
     */
    public final TableField<AlarmRuleRecord, String> SERVICE_TYPE = createField("service_type", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_rule.checker_name</code>.
     */
    public final TableField<AlarmRuleRecord, String> CHECKER_NAME = createField("checker_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_rule.threshold</code>.
     */
    public final TableField<AlarmRuleRecord, Integer> THRESHOLD = createField("threshold", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>pinpoint.alarm_rule.user_group_id</code>.
     */
    public final TableField<AlarmRuleRecord, String> USER_GROUP_ID = createField("user_group_id", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>pinpoint.alarm_rule.sms_send</code>.
     */
    public final TableField<AlarmRuleRecord, String> SMS_SEND = createField("sms_send", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

    /**
     * The column <code>pinpoint.alarm_rule.email_send</code>.
     */
    public final TableField<AlarmRuleRecord, String> EMAIL_SEND = createField("email_send", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

    /**
     * The column <code>pinpoint.alarm_rule.notes</code>.
     */
    public final TableField<AlarmRuleRecord, String> NOTES = createField("notes", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>pinpoint.alarm_rule</code> table reference
     */
    public AlarmRule() {
        this("alarm_rule", null);
    }

    /**
     * Create an aliased <code>pinpoint.alarm_rule</code> table reference
     */
    public AlarmRule(String alias) {
        this(alias, ALARM_RULE);
    }

    private AlarmRule(String alias, Table<AlarmRuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlarmRule(String alias, Table<AlarmRuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AlarmRuleRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ALARM_RULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlarmRuleRecord> getPrimaryKey() {
        return Keys.KEY_ALARM_RULE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlarmRuleRecord>> getKeys() {
        return Arrays.<UniqueKey<AlarmRuleRecord>>asList(Keys.KEY_ALARM_RULE_PRIMARY, Keys.KEY_ALARM_RULE_APPLICATION_ID_CHECKER_NAME_USER_GROUP_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmRule as(String alias) {
        return new AlarmRule(alias, this);
    }

    /**
     * Rename this table
     */
    public AlarmRule rename(String name) {
        return new AlarmRule(name, null);
    }
}
