/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq.tables;


import com.grb.indonesia.jooq.data.jooq.Keys;
import com.grb.indonesia.jooq.data.jooq.Pinpoint;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchJobExecutionContextRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionContext extends TableImpl<BatchJobExecutionContextRecord> {

    private static final long serialVersionUID = 1405293157;

    /**
     * The reference instance of <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT</code>
     */
    public static final BatchJobExecutionContext BATCH_JOB_EXECUTION_CONTEXT = new BatchJobExecutionContext();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchJobExecutionContextRecord> getRecordType() {
        return BatchJobExecutionContextRecord.class;
    }

    /**
     * The column <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID</code>.
     */
    public final TableField<BatchJobExecutionContextRecord, Long> JOB_EXECUTION_ID = createField("JOB_EXECUTION_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT</code>.
     */
    public final TableField<BatchJobExecutionContextRecord, String> SHORT_CONTEXT = createField("SHORT_CONTEXT", org.jooq.impl.SQLDataType.VARCHAR.length(2500).nullable(false), this, "");

    /**
     * The column <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT</code>.
     */
    public final TableField<BatchJobExecutionContextRecord, String> SERIALIZED_CONTEXT = createField("SERIALIZED_CONTEXT", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT</code> table reference
     */
    public BatchJobExecutionContext() {
        this("BATCH_JOB_EXECUTION_CONTEXT", null);
    }

    /**
     * Create an aliased <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT</code> table reference
     */
    public BatchJobExecutionContext(String alias) {
        this(alias, BATCH_JOB_EXECUTION_CONTEXT);
    }

    private BatchJobExecutionContext(String alias, Table<BatchJobExecutionContextRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchJobExecutionContext(String alias, Table<BatchJobExecutionContextRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BatchJobExecutionContextRecord> getPrimaryKey() {
        return Keys.KEY_BATCH_JOB_EXECUTION_CONTEXT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BatchJobExecutionContextRecord>> getKeys() {
        return Arrays.<UniqueKey<BatchJobExecutionContextRecord>>asList(Keys.KEY_BATCH_JOB_EXECUTION_CONTEXT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BatchJobExecutionContextRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BatchJobExecutionContextRecord, ?>>asList(Keys.JOB_EXEC_CTX_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionContext as(String alias) {
        return new BatchJobExecutionContext(alias, this);
    }

    /**
     * Rename this table
     */
    public BatchJobExecutionContext rename(String name) {
        return new BatchJobExecutionContext(name, null);
    }
}
