/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq.tables;


import com.grb.indonesia.jooq.data.jooq.Keys;
import com.grb.indonesia.jooq.data.jooq.Pinpoint;
import com.grb.indonesia.jooq.data.jooq.tables.records.BatchStepExecutionSeqRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchStepExecutionSeq extends TableImpl<BatchStepExecutionSeqRecord> {

    private static final long serialVersionUID = -1279037856;

    /**
     * The reference instance of <code>pinpoint.BATCH_STEP_EXECUTION_SEQ</code>
     */
    public static final BatchStepExecutionSeq BATCH_STEP_EXECUTION_SEQ = new BatchStepExecutionSeq();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchStepExecutionSeqRecord> getRecordType() {
        return BatchStepExecutionSeqRecord.class;
    }

    /**
     * The column <code>pinpoint.BATCH_STEP_EXECUTION_SEQ.ID</code>.
     */
    public final TableField<BatchStepExecutionSeqRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pinpoint.BATCH_STEP_EXECUTION_SEQ.UNIQUE_KEY</code>.
     */
    public final TableField<BatchStepExecutionSeqRecord, String> UNIQUE_KEY = createField("UNIQUE_KEY", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

    /**
     * Create a <code>pinpoint.BATCH_STEP_EXECUTION_SEQ</code> table reference
     */
    public BatchStepExecutionSeq() {
        this("BATCH_STEP_EXECUTION_SEQ", null);
    }

    /**
     * Create an aliased <code>pinpoint.BATCH_STEP_EXECUTION_SEQ</code> table reference
     */
    public BatchStepExecutionSeq(String alias) {
        this(alias, BATCH_STEP_EXECUTION_SEQ);
    }

    private BatchStepExecutionSeq(String alias, Table<BatchStepExecutionSeqRecord> aliased) {
        this(alias, aliased, null);
    }

    private BatchStepExecutionSeq(String alias, Table<BatchStepExecutionSeqRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BatchStepExecutionSeqRecord>> getKeys() {
        return Arrays.<UniqueKey<BatchStepExecutionSeqRecord>>asList(Keys.KEY_BATCH_STEP_EXECUTION_SEQ_UNIQUE_KEY_UN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchStepExecutionSeq as(String alias) {
        return new BatchStepExecutionSeq(alias, this);
    }

    /**
     * Rename this table
     */
    public BatchStepExecutionSeq rename(String name) {
        return new BatchStepExecutionSeq(name, null);
    }
}
