/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq.tables;


import com.grb.indonesia.jooq.data.jooq.Keys;
import com.grb.indonesia.jooq.data.jooq.Pinpoint;
import com.grb.indonesia.jooq.data.jooq.tables.records.UserGroupMemberRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupMember extends TableImpl<UserGroupMemberRecord> {

    private static final long serialVersionUID = -1689127817;

    /**
     * The reference instance of <code>pinpoint.user_group_member</code>
     */
    public static final UserGroupMember USER_GROUP_MEMBER = new UserGroupMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserGroupMemberRecord> getRecordType() {
        return UserGroupMemberRecord.class;
    }

    /**
     * The column <code>pinpoint.user_group_member.number</code>.
     */
    public final TableField<UserGroupMemberRecord, UInteger> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>pinpoint.user_group_member.user_group_id</code>.
     */
    public final TableField<UserGroupMemberRecord, String> USER_GROUP_ID = createField("user_group_id", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>pinpoint.user_group_member.member_id</code>.
     */
    public final TableField<UserGroupMemberRecord, String> MEMBER_ID = createField("member_id", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * Create a <code>pinpoint.user_group_member</code> table reference
     */
    public UserGroupMember() {
        this("user_group_member", null);
    }

    /**
     * Create an aliased <code>pinpoint.user_group_member</code> table reference
     */
    public UserGroupMember(String alias) {
        this(alias, USER_GROUP_MEMBER);
    }

    private UserGroupMember(String alias, Table<UserGroupMemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserGroupMember(String alias, Table<UserGroupMemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pinpoint.PINPOINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserGroupMemberRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_USER_GROUP_MEMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserGroupMemberRecord> getPrimaryKey() {
        return Keys.KEY_USER_GROUP_MEMBER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserGroupMemberRecord>> getKeys() {
        return Arrays.<UniqueKey<UserGroupMemberRecord>>asList(Keys.KEY_USER_GROUP_MEMBER_PRIMARY, Keys.KEY_USER_GROUP_MEMBER_USER_GROUP_ID_MEMBER_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMember as(String alias) {
        return new UserGroupMember(alias, this);
    }

    /**
     * Rename this table
     */
    public UserGroupMember rename(String name) {
        return new UserGroupMember(name, null);
    }
}
