/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq.tables.records;


import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionSeq;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionSeqRecord extends TableRecordImpl<BatchJobExecutionSeqRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1822235184;

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_SEQ.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_SEQ.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_SEQ.UNIQUE_KEY</code>.
     */
    public void setUniqueKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_SEQ.UNIQUE_KEY</code>.
     */
    public String getUniqueKey() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BatchJobExecutionSeq.BATCH_JOB_EXECUTION_SEQ.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BatchJobExecutionSeq.BATCH_JOB_EXECUTION_SEQ.UNIQUE_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUniqueKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionSeqRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionSeqRecord value2(String value) {
        setUniqueKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionSeqRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobExecutionSeqRecord
     */
    public BatchJobExecutionSeqRecord() {
        super(BatchJobExecutionSeq.BATCH_JOB_EXECUTION_SEQ);
    }

    /**
     * Create a detached, initialised BatchJobExecutionSeqRecord
     */
    public BatchJobExecutionSeqRecord(Long id, String uniqueKey) {
        super(BatchJobExecutionSeq.BATCH_JOB_EXECUTION_SEQ);

        set(0, id);
        set(1, uniqueKey);
    }
}
