/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.jooq.data.jooq.tables.records;


import com.grb.indonesia.jooq.data.jooq.tables.BatchJobExecutionParams;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionParamsRecord extends TableRecordImpl<BatchJobExecutionParamsRecord> implements Record8<Long, String, String, String, Timestamp, Long, Double, String> {

    private static final long serialVersionUID = -1524752834;

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID</code>.
     */
    public void setJobExecutionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID</code>.
     */
    public Long getJobExecutionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.TYPE_CD</code>.
     */
    public void setTypeCd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.TYPE_CD</code>.
     */
    public String getTypeCd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.KEY_NAME</code>.
     */
    public void setKeyName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.KEY_NAME</code>.
     */
    public String getKeyName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.STRING_VAL</code>.
     */
    public void setStringVal(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.STRING_VAL</code>.
     */
    public String getStringVal() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.DATE_VAL</code>.
     */
    public void setDateVal(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.DATE_VAL</code>.
     */
    public Timestamp getDateVal() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.LONG_VAL</code>.
     */
    public void setLongVal(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.LONG_VAL</code>.
     */
    public Long getLongVal() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL</code>.
     */
    public void setDoubleVal(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL</code>.
     */
    public Double getDoubleVal() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING</code>.
     */
    public void setIdentifying(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING</code>.
     */
    public String getIdentifying() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, Timestamp, Long, Double, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, Timestamp, Long, Double, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.TYPE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.KEY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.STRING_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.DATE_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.LONG_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getJobExecutionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTypeCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getKeyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStringVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDateVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getLongVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getDoubleVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIdentifying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value1(Long value) {
        setJobExecutionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value2(String value) {
        setTypeCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value3(String value) {
        setKeyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value4(String value) {
        setStringVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value5(Timestamp value) {
        setDateVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value6(Long value) {
        setLongVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value7(Double value) {
        setDoubleVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord value8(String value) {
        setIdentifying(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionParamsRecord values(Long value1, String value2, String value3, String value4, Timestamp value5, Long value6, Double value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobExecutionParamsRecord
     */
    public BatchJobExecutionParamsRecord() {
        super(BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS);
    }

    /**
     * Create a detached, initialised BatchJobExecutionParamsRecord
     */
    public BatchJobExecutionParamsRecord(Long jobExecutionId, String typeCd, String keyName, String stringVal, Timestamp dateVal, Long longVal, Double doubleVal, String identifying) {
        super(BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS);

        set(0, jobExecutionId);
        set(1, typeCd);
        set(2, keyName);
        set(3, stringVal);
        set(4, dateVal);
        set(5, longVal);
        set(6, doubleVal);
        set(7, identifying);
    }
}
