/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables.records;


import com.grb.indonesia.entity.tables.AlarmHistory;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmHistoryRecord extends UpdatableRecordImpl<AlarmHistoryRecord> implements Record6<UInteger, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = -1642002866;

    /**
     * Setter for <code>pinpoint.alarm_history.history_id</code>.
     */
    public void setHistoryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>pinpoint.alarm_history.history_id</code>.
     */
    public UInteger getHistoryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>pinpoint.alarm_history.application_id</code>.
     */
    public void setApplicationId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pinpoint.alarm_history.application_id</code>.
     */
    public String getApplicationId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pinpoint.alarm_history.checker_name</code>.
     */
    public void setCheckerName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pinpoint.alarm_history.checker_name</code>.
     */
    public String getCheckerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pinpoint.alarm_history.detected</code>.
     */
    public void setDetected(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pinpoint.alarm_history.detected</code>.
     */
    public String getDetected() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pinpoint.alarm_history.sequence_count</code>.
     */
    public void setSequenceCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>pinpoint.alarm_history.sequence_count</code>.
     */
    public Integer getSequenceCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>pinpoint.alarm_history.timing_count</code>.
     */
    public void setTimingCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>pinpoint.alarm_history.timing_count</code>.
     */
    public Integer getTimingCount() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, String, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, String, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return AlarmHistory.ALARM_HISTORY.HISTORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AlarmHistory.ALARM_HISTORY.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AlarmHistory.ALARM_HISTORY.CHECKER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AlarmHistory.ALARM_HISTORY.DETECTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return AlarmHistory.ALARM_HISTORY.SEQUENCE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return AlarmHistory.ALARM_HISTORY.TIMING_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getHistoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCheckerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDetected();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSequenceCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTimingCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistoryRecord value1(UInteger value) {
        setHistoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistoryRecord value2(String value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistoryRecord value3(String value) {
        setCheckerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistoryRecord value4(String value) {
        setDetected(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistoryRecord value5(Integer value) {
        setSequenceCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistoryRecord value6(Integer value) {
        setTimingCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmHistoryRecord values(UInteger value1, String value2, String value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlarmHistoryRecord
     */
    public AlarmHistoryRecord() {
        super(AlarmHistory.ALARM_HISTORY);
    }

    /**
     * Create a detached, initialised AlarmHistoryRecord
     */
    public AlarmHistoryRecord(UInteger historyId, String applicationId, String checkerName, String detected, Integer sequenceCount, Integer timingCount) {
        super(AlarmHistory.ALARM_HISTORY);

        set(0, historyId);
        set(1, applicationId);
        set(2, checkerName);
        set(3, detected);
        set(4, sequenceCount);
        set(5, timingCount);
    }
}
