/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables.records;


import com.grb.indonesia.entity.tables.BatchJobExecution;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionRecord extends UpdatableRecordImpl<BatchJobExecutionRecord> implements Record10<Long, Long, Long, Timestamp, Timestamp, Timestamp, String, String, String, Timestamp> {

    private static final long serialVersionUID = -854659889;

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.JOB_EXECUTION_ID</code>.
     */
    public void setJobExecutionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.JOB_EXECUTION_ID</code>.
     */
    public Long getJobExecutionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.VERSION</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.VERSION</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.JOB_INSTANCE_ID</code>.
     */
    public void setJobInstanceId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.JOB_INSTANCE_ID</code>.
     */
    public Long getJobInstanceId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.CREATE_TIME</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.CREATE_TIME</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.START_TIME</code>.
     */
    public void setStartTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.START_TIME</code>.
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.END_TIME</code>.
     */
    public void setEndTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.END_TIME</code>.
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.STATUS</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.EXIT_CODE</code>.
     */
    public void setExitCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.EXIT_CODE</code>.
     */
    public String getExitCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.EXIT_MESSAGE</code>.
     */
    public void setExitMessage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.EXIT_MESSAGE</code>.
     */
    public String getExitMessage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION.LAST_UPDATED</code>.
     */
    public void setLastUpdated(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION.LAST_UPDATED</code>.
     */
    public Timestamp getLastUpdated() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Timestamp, Timestamp, Timestamp, String, String, String, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Timestamp, Timestamp, Timestamp, String, String, String, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.JOB_EXECUTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.JOB_INSTANCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.EXIT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.EXIT_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return BatchJobExecution.BATCH_JOB_EXECUTION.LAST_UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getJobExecutionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getJobInstanceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getExitCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getExitMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value1(Long value) {
        setJobExecutionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value3(Long value) {
        setJobInstanceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value5(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value6(Timestamp value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value8(String value) {
        setExitCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value9(String value) {
        setExitMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord value10(Timestamp value) {
        setLastUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionRecord values(Long value1, Long value2, Long value3, Timestamp value4, Timestamp value5, Timestamp value6, String value7, String value8, String value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobExecutionRecord
     */
    public BatchJobExecutionRecord() {
        super(BatchJobExecution.BATCH_JOB_EXECUTION);
    }

    /**
     * Create a detached, initialised BatchJobExecutionRecord
     */
    public BatchJobExecutionRecord(Long jobExecutionId, Long version, Long jobInstanceId, Timestamp createTime, Timestamp startTime, Timestamp endTime, String status, String exitCode, String exitMessage, Timestamp lastUpdated) {
        super(BatchJobExecution.BATCH_JOB_EXECUTION);

        set(0, jobExecutionId);
        set(1, version);
        set(2, jobInstanceId);
        set(3, createTime);
        set(4, startTime);
        set(5, endTime);
        set(6, status);
        set(7, exitCode);
        set(8, exitMessage);
        set(9, lastUpdated);
    }
}
