/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables.records;


import com.grb.indonesia.entity.tables.BatchJobExecutionContext;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionContextRecord extends UpdatableRecordImpl<BatchJobExecutionContextRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = -960442321;

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID</code>.
     */
    public void setJobExecutionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID</code>.
     */
    public Long getJobExecutionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT</code>.
     */
    public void setShortContext(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT</code>.
     */
    public String getShortContext() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT</code>.
     */
    public void setSerializedContext(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pinpoint.BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT</code>.
     */
    public String getSerializedContext() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getJobExecutionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getShortContext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSerializedContext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionContextRecord value1(Long value) {
        setJobExecutionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionContextRecord value2(String value) {
        setShortContext(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionContextRecord value3(String value) {
        setSerializedContext(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchJobExecutionContextRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobExecutionContextRecord
     */
    public BatchJobExecutionContextRecord() {
        super(BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT);
    }

    /**
     * Create a detached, initialised BatchJobExecutionContextRecord
     */
    public BatchJobExecutionContextRecord(Long jobExecutionId, String shortContext, String serializedContext) {
        super(BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT);

        set(0, jobExecutionId);
        set(1, shortContext);
        set(2, serializedContext);
    }
}
