/**
 * This class is generated by jOOQ
 */
package com.grb.indonesia.entity.tables.records;


import com.grb.indonesia.entity.tables.UserGroupMember;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupMemberRecord extends UpdatableRecordImpl<UserGroupMemberRecord> implements Record3<UInteger, String, String> {

    private static final long serialVersionUID = -1992270629;

    /**
     * Setter for <code>pinpoint.user_group_member.number</code>.
     */
    public void setNumber(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>pinpoint.user_group_member.number</code>.
     */
    public UInteger getNumber() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>pinpoint.user_group_member.user_group_id</code>.
     */
    public void setUserGroupId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pinpoint.user_group_member.user_group_id</code>.
     */
    public String getUserGroupId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pinpoint.user_group_member.member_id</code>.
     */
    public void setMemberId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pinpoint.user_group_member.member_id</code>.
     */
    public String getMemberId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return UserGroupMember.USER_GROUP_MEMBER.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserGroupMember.USER_GROUP_MEMBER.USER_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserGroupMember.USER_GROUP_MEMBER.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value1(UInteger value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value2(String value) {
        setUserGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord value3(String value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupMemberRecord values(UInteger value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserGroupMemberRecord
     */
    public UserGroupMemberRecord() {
        super(UserGroupMember.USER_GROUP_MEMBER);
    }

    /**
     * Create a detached, initialised UserGroupMemberRecord
     */
    public UserGroupMemberRecord(UInteger number, String userGroupId, String memberId) {
        super(UserGroupMember.USER_GROUP_MEMBER);

        set(0, number);
        set(1, userGroupId);
        set(2, memberId);
    }
}
